In [1]:
# Consider the below code to answer further questions:

import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_)

In [2]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.

## list_ contains string elements.
## array_list also contains string elements, but as a NumPy array.

print(f"Data type of elements in list_: {type(list_[0])}")
print(f"Data type of elements in array_list: {array_list.dtype}")

Data type of elements in list_: <class 'str'>
Data type of elements in array_list: <U1


In [3]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list

print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")

Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


In [4]:
#Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list.


## Yes, there will be a difference in the data types of the elements in list_ and array_list after changing array_list to dtype=int. Here's a breakdown of the differences:

##list_: This will remain a Python list with elements of type str (string).
## array_list: This will be a NumPy array with elements converted to int (integer) due to the specified dtype=int

print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")

Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.int64'>
Element: 2, Type: <class 'numpy.int64'>
Element: 3, Type: <class 'numpy.int64'>
Element: 4, Type: <class 'numpy.int64'>
Element: 5, Type: <class 'numpy.int64'>


In [5]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [7]:
# Q4. Write a code to find the following characteristics of variable, num_array:

# (i)shape
print(num_array.shape)

# (ii) size
print(num_array.size)

(2, 3)
6


In [8]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.

# [Hint: The size of the array will be 9 and the shape will be (3,3).]

zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
